### ISSUE TITLE
Use LESS or SASS instead of CSS.

### ISSUE THREAD

**Issue by Etheryte** [travs/markdown-pdf#130]
The current [`github-markdown.css`](https://github.com/travs/markdown-pdf/blob/master/lib/github-markdown.css) contains a lot of repetitive selectors as well as many nested selectors. Most of these could be written more concisely using a CSS preprocessor.

CSS:

``` css
.markdown-body ul,
.markdown-body ol {
  padding: 0;
  margin-top: 0;
  margin-bottom: 0;
}

.markdown-body ol ol,
.markdown-body ul ol {
  list-style-type: lower-roman;
}

.markdown-body ul ul ol,
.markdown-body ul ol ol,
.markdown-body ol ul ol,
.markdown-body ol ol ol {
  list-style-type: lower-alpha;
}
```

Equivalent LESS/SASS:

``` css
.markdown-body {
  ul,
  ol {
    padding: 0;
    margin-top: 0;
    margin-bottom: 0;

    ol {
      list-style-type: lower-roman;
    }

    ul,
    ol {
     ol {
       list-style-type: lower-alpha;
     }
    }

  }
}
```

Numerous other places apply similarily.

While personally I strongly prefer SASS, [LESS is already a dependency for the project](https://github.com/travs/markdown-pdf/blob/master/package.json). It would be a waste not to put it to good use.
