### ISSUE TITLE
Code block in PDF has a scroll bar

### ISSUE THREAD

**Issue by dotnetdan** [travs/markdown-pdf#21]
This is a picture of the actual PDF... and sadly, the scrollbar is not interactive :smiley: 

![image](https://cloud.githubusercontent.com/assets/500965/5599923/e7a11a32-929d-11e4-92fd-cc13a26e2864.png)

**Comment by marcbachmann** [comment]
lol. The css needs an update. Strange behaviour of phantomjs

**Comment by intcreator** [comment]
This is still an issue.  The scrollbar doesn't even match the operating system.  I'm running Mac OS X and yet the scrollbar looks like it's from Windows 95.

**Comment by amithm7** [comment]
Two years on, still an issue. @travs Working on it or ignored?

**Comment by amwk** [comment]
+1 with this scrollbar, package is not very usefull :(

**Comment by rgarrigue** [comment]
Will this be ever resolved ?

**Comment by amithm7** [comment]
I am using [this](https://github.com/cakebake/markdown-themeable-pdf) package if anyone is interested, no scrollbars.

**Comment by travs** [comment]
@BlueHatbRit
Do you think we should add support for code block text-wrapping here or in `mdpdf`?
I would be happy to add it here if it makes more sense.

Also, do you know how to support this?
I have tried adding options in atom's user styles like this:
```css
pre {
    white-space: pre-wrap !important;       /* Since CSS 2.1 */
    white-space: -moz-pre-wrap !important;  /* Mozilla, since 1999 */
    white-space: -pre-wrap !important;      /* Opera 4-6 */
    white-space: -o-pre-wrap !important;    /* Opera 7 */
    word-wrap: break-word !important;       /* Internet Explorer 5.5+ */
    overflow: hidden !important;
}
``` 
and this gets added to the `styles` key in the object I pass into `mdpdf`, but the text block does not seems to wrap. Have confirmed as well that this CSS is added to the HTML that `mdpdf` uses before making the pdf.

**Comment by BlueHatbRit** [comment]
@travs I think this makes sense to include in include in the mdpdf base styling, before I do that though it'd be good to see if this css fixes the issue for you. I tested the following through mdpdf, not markdown-pdf so it may need a few tweaks but should work just fine.

```css
pre, code {
    white-space: normal;
}
```

**Comment by travs** [comment]
@BlueHatbRit 
Slowpoke here, only this works for me (small tweak):

```
pre, code {
      white-space: normal !important;
}
```

**Comment by BlueHatbRit** [comment]
I passed my snippet in with the styles option as well, are you trying it through markdown-pdf or through mdpdf directly?

**Comment by travs** [comment]
@BlueHatbRit 
Ah sorry forgot to mention this was just through `markdown-pdf`

**Comment by BlueHatbRit** [comment]
That's interesting, does your styles.less have anything else inside it? I'm guessing not but it's worth checking.

**Comment by travs** [comment]
@BlueHatbRit 
There are a few empty selectors there, just as the Atom default I suppose.
The full file is like this:
```less
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed and saved.
 *
 * Add your own CSS or Less to fully customize Atom.
 * If you are unfamiliar with Less, you can read more about it here:
 * http://lesscss.org
 */


/*
 * Examples
 * (To see them, uncomment and save)
 */

// style the background color of the tree view
.tree-view {
  // background-color: whitesmoke;
}

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
  // color: white;
  // background-color: hsl(180, 24%, 12%);
}

// style UI elements inside atom-text-editor
atom-text-editor .cursor {
  // border-color: red;
}
```

**Comment by BlueHatbRit** [comment]
Weird, I'm not sure why you need to add `!important` to that, I'll have a play through atom and see what I can do, it'd be nice not to add something like `!important` to the mdpdf base CSS if we can help it.

Are you using all the mdpdf default styles (the github styles, etc)?

**Comment by nbari** [comment]
Any update on this?

**Comment by travs** [comment]
@BlueHatbRit Sorry for the late reply again, but yes I am using the default styles as far as I know (`ghStyle: true`)

**Comment by travs** [comment]
@BlueHatbRit 

>  it'd be nice not to add something like !important to the mdpdf base CSS if we can help it.

Seems like it was because of the comma in the selector, all you need is:

```css
.markdown-body pre code {
    white-space: pre-wrap;
}
```
