### ISSUE TITLE
adding custom css file inside markdown file

### ISSUE THREAD

**Issue by mostafahussein** [travs/markdown-pdf#41]
is there a way to use css and make it printable ?

it works in markdown-preview but when i print it i got error while converting
I know you cannot use markdown inside a div.
if i created a custom css file and give additional css to 

``` css
.mardown-preview: {
background-image: url(https://octodex.github.com/images/gobbleotron.gif);
 } 
```

then include it inside my markdown it will fail when converting like the screenshot below.

it only works if i modified mardown-preview.less itself.

![screenshot from 2015-02-14 11 19 49](https://cloud.githubusercontent.com/assets/4104127/6199254/1fbc9878-b441-11e4-96be-4e413b9bad72.png)
